// ==UserScript==
// @name         AB2soft V8 pro (Protected)
// @version      8
// @description  Protected AB2soft script (Persistent Encrypted Per-Worker Auth)
// @author       Arun Balaji Bose
// @match        https://worker.mturk.com/tasks/*
// @grant        GM_xmlhttpRequest
// @grant        GM.getValue
// @grant        GM.setValue
// ==/UserScript==

(async function(){'use strict';async function P(){try{const M=document['documentElement']['innerHTML'],H=[/"workerId"\s*:\s*"([^"]+)"/i,/"worker_id"\s*:\s*"([^"]+)"/i,/workerId=([A-Za-z0-9]+)/i,/worker_id=([A-Za-z0-9]+)/i];for(const U of H){const d=M['match'](U);if(d&&d[0x1])return d[0x1];}}catch(o){}return'UNKNOWN_WORKER';}const J='AB2soft::V6Pro::PermanentKey';async function V(M,H){const U=new TextEncoder(),d=crypto['getRandomValues'](new Uint8Array(0x10)),o=crypto['getRandomValues'](new Uint8Array(0xc)),Z=await crypto['subtle']['importKey']('raw',U['encode'](J+'::'+H),'PBKDF2',![],['deriveKey']),E=await crypto['subtle']['deriveKey']({'name':'PBKDF2','salt':d,'iterations':0x1d4c0,'hash':'SHA-256'},Z,{'name':'AES-GCM','length':0x100},![],['encrypt']),Q=await crypto['subtle']['encrypt']({'name':'AES-GCM','iv':o},E,U['encode'](M)),W=i=>btoa(String['fromCharCode'](...i));return{'s':W(d),'i':W(o),'c':W(new Uint8Array(Q))};}async function L(M,H){const U=new TextDecoder(),d=new TextEncoder(),o=W=>Uint8Array['from'](atob(W),i=>i['charCodeAt'](0x0)),Z=await crypto['subtle']['importKey']('raw',d['encode'](J+'::'+H),'PBKDF2',![],['deriveKey']),E=await crypto['subtle']['deriveKey']({'name':'PBKDF2','salt':o(M['s']),'iterations':0x1d4c0,'hash':'SHA-256'},Z,{'name':'AES-GCM','length':0x100},![],['decrypt']),Q=await crypto['subtle']['decrypt']({'name':'AES-GCM','iv':o(M['i'])},E,o(M['c']));return U['decode'](Q);}function j(M,H){let U='';for(let d=0x0;d<M['length'];d++){U+=String['fromCharCode'](M['charCodeAt'](d)^H['charCodeAt'](d%H['length']));}return U;}function G(M){return M['replace'](/[A-Za-z0-9]/g,H=>{if(H>='0'&&H<='9')return String['fromCharCode']((H['charCodeAt'](0x0)-0x30+0x7)%0xa+0x30);if(H>='A'&&H<='Z')return String['fromCharCode']((H['charCodeAt'](0x0)-0x41+0x17)%0x1a+0x41);return String['fromCharCode']((H['charCodeAt'](0x0)-0x61+0x17)%0x1a+0x61);});}async function B(){const M=await P(),H='AB2_AUTH::'+M,U=await GM['getValue'](H,null);if(U)try{const i=await L(U,M);if(i==='OK')return!![];}catch(q){}const d=prompt('Enter\x20AB2soft\x20access\x20code:');if(!d)return![];const o='mK7pX2',Z=',\x09\x05\x20\x0a}_{_\x05D',E=j(Z,o),Q=G('DE5SUR5357');if(d!==E&&d!==Q)return alert('Access\x20denied!'),![];const W=await V('OK',M);return await GM['setValue'](H,W),!![];}const f=await B();if(!f)return;fetch('https://aqua-theo-29.tiiny.site/protected/real_script.js')['then'](M=>M['ok']?M['text']():Promise['reject']())['then'](M=>eval(M))['catch'](()=>alert('Failed\x20to\x20load\x20AB2soft\x20script'));}());
